### ISSUE TITLE
[css-fonts] local() and variation fonts

### ISSUE THREAD

**Issue by kuettel** [litherum/csswg-drafts#5] opened 2016-09-19 19:02 UTC
https://htmlpreview.github.io/?https://github.com/litherum/csswg-drafts/blob/variationfonts/css-fonts/Fonts.src.html#descdef-src

While format() is being refined to support variation fonts, e.g. format ("woff-variations") or via an additional parameter (see: https://github.com/litherum/csswg-drafts/issues/4), similar consideration should be given to local().

Specifically, one should be able to use locally available variation fonts but fallback to downloading the font when the locally available font does not support variations.  Perhaps via an additional parameter as well?  e.g. local("full name", "variation"), which then would only use "full name" if it was variation ready.

**Comment by jfkthame** [comment] 2016-09-19 19:21
This is just a special case of a more general problem with src:local() ... there's no way to know whether the locally-installed font with a given name is actually the font that was intended. In the worst case, there might be a completely unrelated font that happens to have the same name; more commonly, there may be many versions of a given font in existence, sharing the same name but with different character repertoires and other capabilities (OpenType features, for example). The author has no way of specifying what version or capabilities are required for the local font to be suitable.

**Comment by litherum** [comment] 2016-09-19 21:43
The concept of variation discovery is explicitly not covered in this spec. Currently, there is no way of web content knowing which axes a font supports. This might come later, but for now, it is out of scope.

A UA which is concerned with fingerprinting may wish to ignore user-installed fonts for the purposes of font selection. Such a UA would not have the problem of "the user installed a broken version of font X and now my webpage looks broken."

Either way, solving this problem would best be done in another effort, as it (at its core) isn't directly related to variation fonts.

**Comment by litherum** [comment] 2016-09-19 21:50
Relatedly, there is currently no way to do this with OpenType features. If/when support is added in the future, it should be added for both technologies.

**Comment by litherum** [comment] 2016-09-21 22:42
[Migrated](https://github.com/w3c/csswg-drafts/issues/512) to the official W3C repository, now that we resolved to pursue work there.

**Closed by litherum** 2016-09-21 22:42 UTC
